import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Inter } from 'next/font/google'
import SparklesIcon from "./components/SparklesIcon";

const inter = Inter({subsets:['latin']})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
    className={`${inter.className} bg-gradient-to-b from-gradientFrom to-gradientTo min-h-screen text-white`}
    >

        <main className="p-4 max-w-2xl mx-auto">
          <header className="flex justify-between my-2 sm:my-8 ">
                  <Link href="/" className="flex gap-1">
                    <SparklesIcon />
          
                    <span>Ultimate Captions</span></Link>
                  <nav className="flex items-center gap-2 sm:gap-6 text-white/80 text-sm sm:text-base">
                    <Link href="/">Home</Link>
                    <Link href="/pricing">Pricing</Link>
                    <Link href="/contatcs">Contacts</Link>
                  </nav>
                </header>
          {children}
        </main>
      </body>
    </html>
  );
}
